"""empty message

Revision ID: 5978d4b1c149
Revises: 79c90d6ecf26
Create Date: 2023-02-19 03:33:57.986219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5978d4b1c149'
down_revision = '79c90d6ecf26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
